sudo: required
language: python
services:
  - rabbitmq
python:
  - "3.6"
before_install:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo /etc/init.d/rabbitmq-server restart
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pip check
  - python test/runtests.py --use-local
notifications:
  irc: "irc.mozilla.org#pulse"
  on_success: change
addons:
  apt:
    packages:
    - rabbitmq-server
